name: temporary-deployment
on:
  push:
    branches:
      - publish
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: using ssh for deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /var/publish-dir/crypithm-backend
          sudo git pull
          sudo go build server.go
          sudo mv server /var/www/api
          sudo systemctl restart crypithmserver