name: temporary-deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: using ssh for deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          sudo su
          cd /var/publish-dir/crypithm-backend
          git pull
          go build server.go
          mv server /var/www/api
          systemctl restart crypithmserver